CREATE TABLE notifications (
 ID BIGINT AUTO_INCREMENT PRIMARY KEY AUTO_INCREMENT,
 title VARCHAR(255) NOT NULL,
 message TEXT NOT NULL,
 sent_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 is_read BOOLEAN DEFAULT FALSE,
 tenant_id BIGINT NOT NULL,
 recipient_id BIGINT NOT NULL,
 CONSTRAINT fk_notification_user FOREIGN KEY (recipient_id) REFERENCES user(id) ON DELETE CASCADE
);